### ISSUE TITLE
Proposal: Filename field as path

### ISSUE THREAD

**Issue by max-gram** [freshheads/svg-spritemap-webpack-plugin#10]
Hey, I'm wondering if there is any specific reason output file is locked to `output.path`?
I'm working on the setup where I need to compile svg into `/public` path, which is outside `output.path` folder.  Would you consider pull request for it? Or maybe you can recommend some solutions with "as is" code? All I could come up with - a package scripts command to build svg by `npm run svg`, but I'd like it to be automated.

**Comment by cascornelissen** [comment]
The only reason it's set up like this is because Webpack does it this way. Are you using anything else within Webpack that outputs to a path outside the build directory?

If so; I'd accept a PR but it feels like this goes against the way Webpack does stuff...

**Comment by max-gram** [comment]
Yeah, actually none libs I'm using do that, so I guess you are right, it should stay this way. Thanks!
Closing
