### ISSUE TITLE
Can I put two routes into scr attribute?

### ISSUE THREAD

**Issue by ctkc** [freshheads/svg-spritemap-webpack-plugin#13]
Hello, I need to put two routes with different files, Is there a way to do this?.

Thanks a lot!

**Comment by cascornelissen** [comment]
The ‘src’ option supports [globbing](https://www.npmjs.com/package/glob), which also supports something like `(a|b)` for ORs.

Either that or you could add two seperate instance of the plugin to your plugins array in your configuration if you want two seperate SVGs as output.

Let me know!

**Comment by cascornelissen** [comment]
@ctkc, any updates on this?

**Comment by ctkc** [comment]
I wanted merge two different inputs into the same output file. If I put two instances of the same plugin with the same output, the second instance override the file so it is not what I need but thanks a lot for your answer.

**Comment by cascornelissen** [comment]
If you're still trying to do that, it's possible to do this through [globbing](https://www.npmjs.com/package/glob), something like the following should work:

```
{
    src: '{path/to/one/directory,path/to/another/directory}/**/*.svg'
    // ...
}
```
If you need any more info; this [glob primer](https://github.com/isaacs/node-glob#glob-primer) explains it pretty well

**Comment by ctkc** [comment]
It works!. Thank you so much!

**Comment by cascornelissen** [comment]
Great! No problem at all! 😄

**Comment by gabolecointere** [comment]
Hello @cascornelissen relateted to this! IF I have SVGs grouped into folders for each page and I want to create one Sprite for each page, u recommend to do it with multiple separate instances? 

I guess that's the way to go, thanks in advance

**Comment by cascornelissen** [comment]
Yeah, if you want to create separate spritemaps then multiple instances would be the way to go 😉

**Comment by gabolecointere** [comment]
@cascornelissen hey sorry, another questions, how can I make the Id value the same as the svg element that gets into the sprite?

Right now I have flags and I would like to use them by the locale like en, es, fr for the IDs, and the plugin assigns numbers to the Sprites. Do you have an advice about this? I'm in 1.2.0 because my webpack version is not the last one

**Comment by gabolecointere** [comment]
Just providing more info: The files that are in the folder, have the locale name like en.svg es.svg etc and I would like to preserve it for the IDs

**Comment by danew** [comment]
By default the id is the svg files name, if you want to have separate sprites per locale you can use the prefix similar to what I've done [here](https://github.com/danew/hashed-svg-spritesheet/blob/master/webpack.config.js#L6), this way you can have a directory per locale.

**Comment by cascornelissen** [comment]
@gabolecointere, I'm afraid you'll have to update to the latest major version for this.

**Comment by gabolecointere** [comment]
I just upgraded and I have two issues: npm run dev and watch produces the build but npm run prod returns an issue like: Unknown Word

When the build runs with npm run dev, my sprites.svg file it's empty :( This is my webpack config:

`plugins: [
        new CopyWebpackPlugin([{
            from: 'resources/assets/img',
            to: 'img', // Laravel mix will place this in 'public/img'
        }]),
        new ImageminPlugin({
            test: /\.(jpe?g|png|gif|svg)$/i,
            plugins: [
                imageminMozjpeg({
                    quality: 80,
                })
            ]
        }),
        new SVGSpritemapPlugin('resources/assets/img/header/round-flags/*.svg', {
            output: {
                filename: 'img/sprites.svg',
                chunk: {
                    name: 'img/spritemap',
                    keep: true 
                }
            }
        })
    ]`

**Comment by cascornelissen** [comment]
@gabolecointere, can you create a new (well-formatted) issue with a minimal test case that fails for you?
