### ISSUE TITLE
Output: viewBox="NaN"

### ISSUE THREAD

**Issue by remco-freshheads** [freshheads/svg-spritemap-webpack-plugin#15]
When I run svg's through this plugin without the attribute viewBox set, the output of the particular svg will contain the `viewBox` attribute set to `NaN`.  I often use svg's with width and height set, instead of viewBox.

Most of the time I solved it by setting the `viewBox`. In the example below I changed `width="357" height="357"` to `viewBox="0 0 357 357"`, but this shouldn't be necessary. 

Example of svg *before* webpack:
```
<svg xmlns="http://www.w3.org/2000/svg" width="357" height="357">
    <path fill="#000" d="M357 35.7L321.3 0 178.5 142.8 35.7 0 0 35.7l142.8 142.8L0 321.3 35.7 357l142.8-142.8L321.3 357l35.7-35.7-142.8-142.8z"/>
</svg>
```

Example of symbol *after* webpack:
```
<symbol id="sprite-cancel-test" viewBox="NaN">
    <title>cancel-test</title>
    <path d="M357 35.7L321.3 0 178.5 142.8 35.7 0 0 35.7l142.8 142.8L0 321.3 35.7 357l142.8-142.8L321.3 357l35.7-35.7-142.8-142.8z"/>
</symbol>
<use xlink:href="#sprite-cancel-test" width="357" height="357"/>
```

**Comment by cascornelissen** [comment]
This has been fixed in `1.0.4` 🎉
