### ISSUE TITLE
Proposal: make deletion of chunked .js configurable

### ISSUE THREAD

**Issue by nelsonkyshin** [freshheads/svg-spritemap-webpack-plugin#17]
At the end of webpack compilation, I receive EOENT because the created 'spritemap.js' is no longer there. This may be because of other reporting tools in the stack.

A parameter in the options to not delete the .js file would be helpful

**Comment by cascornelissen** [comment]
Sounds like a valid use case, I'm happy to accept a PR. If you don't have time to fix it yourself and submit a PR I'll have some time this weekend to look at it as well 😉

**Comment by nelsonkyshin** [comment]
Oops I was on vacation the last few days :) PR is open
https://github.com/freshheads/svg-spritemap-webpack-plugin/pull/18

**Comment by cascornelissen** [comment]
Fixed in `1.1.0` (#18)
