### ISSUE TITLE
Webpack uglify fails

### ISSUE THREAD

**Issue by cwirz** [freshheads/svg-spritemap-webpack-plugin#6]
The webpack uglify plugin fails if you run `webpack -p`

Error message:
```
ERROR in UglifyEsPlugin - spritemap.svg
{"message":"Unexpected token: operator (<)","filename":"spritemap.svg","line":1,"col":0,"pos":0}
```

Any idea how to solve this issue?

**Comment by cascornelissen** [comment]
I can't seem to reproduce this issue. It looks like it's trying to parse the SVG as JS which throws the error you've provided.

Could you provide a minimal test case?

**Comment by cwirz** [comment]
I've just included the plugin in the webpack config file like this and ran the command `webpack -p`

```
module.exports.plugins = (module.exports.plugins || []).concat([
    new SVGSpritemapPlugin({
        src: './assets/**/*.svg',
        prefix: 'icon-',
    }),
])
```

When i do the `webpack --watch` command it creates the `spritemap.svg` file.

**Comment by cascornelissen** [comment]
Could you provide the entire webpack configuration in this issue or (even better) a link to the project so I can test this? I suspect something goes wrong with production-specific loader configuration but I'm not sure as I don't know anything about your setup.

**Comment by cwirz** [comment]
I'm using now a workaroud to build the spritemap file first in the development process and exclude later the plugin in the production build but this feels wrong...

```
const path = require('path')
const webpack = require('webpack')
const SVGSpritemapPlugin = require('svg-spritemap-webpack-plugin')
const CopyWebpackPlugin = require('copy-webpack-plugin')
const UglifyEsPlugin = require('uglify-es-webpack-plugin')

process.env.BABEL_ENV = 'app'

module.exports = {
    entry: {
        renderer: path.join(__dirname, 'app/main.js')
    },
    output: {
        path: path.resolve(__dirname, './app-dist'),
        libraryTarget: 'commonjs2',
        filename: 'build.js'
    },
    resolve: {
        extensions: ['.js', '.vue', '.scss'],
        alias: {
            vue: 'vue/dist/vue.js'
        }
    },
    target: 'electron-renderer',
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader:  'vue-loader',
                options: {
                    loaders: {
                        'scss': 'vue-style-loader!css-loader!sass-loader',
                        'sass': 'vue-style-loader!css-loader!sass-loader?indentedSyntax',
                        'js': 'babel-loader!eslint-loader'
                    },
                },
                include: [
                    path.resolve(__dirname, "app/"),
                ],
            },
            {
                test: /\.js$/,
                loaders: [
                    'babel-loader',
                    'eslint-loader',
                ],
                include: [
                    path.resolve(__dirname, "app/"),
                ],
            },
        ]
    },
    plugins: [
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.DefinePlugin({
            'process.env.LATER_COV': false,
        }),
        new CopyWebpackPlugin([
            {from: 'app/index.html'},
            {from: 'node_modules/terminal-notifier/terminal-notifier.app/Contents/MacOS/terminal-notifier'},
        ], {}),
    ],
    node: {
        __filename: true,
        __dirname: true
    }
}


if (process.env.NODE_ENV === 'developemnt') {
    module.exports.plugins = (module.exports.plugins || []).concat([
        new SVGSpritemapPlugin({
            src: './assets/**/*.svg',
            prefix: 'icon-',
        }),
    ])
}
if (process.env.NODE_ENV === 'production') {
    module.exports.devtool = 'source-map'
    module.exports.plugins = (module.exports.plugins || []).concat([
        new UglifyEsPlugin(),
    ])
}
```

**Comment by cascornelissen** [comment]
Does excluding the `spritemap.svg` using the [`exclude` option](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#options) from `uglifyjs-webpack-plugin` not work?

**Comment by cwirz** [comment]
Not tried it yet but shouldn't that be a problem because the uglifyjs tries to uglify only js files?

**Comment by cascornelissen** [comment]
Yeah, I noticed the `test` option too. I'm willing to look into the issue regarding the fact that it tries to minify a file that doesn't pass the `test` but I'm short on time for the upcoming weeks so I'm looking for a solution to your problem in the meantime.

**Comment by cwirz** [comment]
Cool thanks. Helps me a lot and thanks also for the great plugin!

**Comment by cascornelissen** [comment]
You're more than welcome! I'll keep the issue open so I don't forget to look into this when I have the time.

**Comment by cascornelissen** [comment]
I've been looking into this for the last hour but can't really replicate the issue. When someone runs into this problem and can submit a working test case I'd be happy to look into it once more.
