### ISSUE TITLE
Can you make "svgo" a peer dependancy?

### ISSUE THREAD

**Issue by vzaidman** [freshheads/svg-spritemap-webpack-plugin#8]
for example for people who wants to use a custom version of it with my own plugins.
or custom version

**Comment by cascornelissen** [comment]
I'd be willing to accept a PR for this, yeah 😉

**Comment by vzaidman** [comment]
np

**Comment by cascornelissen** [comment]
Closing the issue, if anyone wants to move the `svgo` dependency to a peer dependency and add a warning for when `svgo` is not installed: feel free to submit a PR 👍
